### ISSUE TITLE
Atrium_folder error when update files

### ISSUE THREAD

**Issue by mmagnet** [nuvoleweb/atrium_folders#5] opened 2011-05-31 13:48 UTC
> Comment: <p>\* warning: Parameter 2 to notifications_team_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to purl_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to spaces_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to atrium_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to atrium_book_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to casetracker_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to date_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to date_timezone_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to og_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to wysiwyg_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to og_access_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to atrium_folders_form_alter() expected to be a reference, value given in /var/www/includes/common.inc on line 2892.<br />
> - warning: Parameter 2 to notifications_content_form_alter() 
>   expected to be a reference, value given in 
>   /var/www/includes/common.inc on line 2892.</p>

**Comment by mmagnet** [comment] 2011-05-31 13:50
foreach (module_implements($type .'_alter') as $module) {
    $function = $module .'_'. $type .'_alter';
    call_user_func_array($function, $args);
  }

line 2892 =  call_user_func_array($function, $args);

**Comment by nuvoleweb** [comment] 2011-05-31 13:53
Duplicate of #1

**Closed as completed by nuvoleweb** 2011-05-31 13:53 UTC
